name: buniashop
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  supabase: ^2.6.2
  mocktail: ^1.0.4
  supabase_flutter: ^2.8.2
  bloc_test: ^9.1.7
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  localstorage: ^5.0.0
  loading_animation_widget: ^1.3.0
  awesome_dialog: ^3.2.1
  provider: ^6.1.2
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/categories/
    - assets/images/produits/
    - assets/images/publicites/
